version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    depends_on:
      - authentication
      - api
      - reddit
      - llm
    ports:
      - 8000:8000
    volumes:
      - ./api-gateway:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  authentication:
    build: ./authentication
    depends_on:
      - postgres
      - redis
    ports:
      - 8001:8001
    volumes:
      - ./authentication:/usr/src/app:ro
    env_file:
      - ./authentication/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001

  api:
    build: ./youtube
    depends_on:
      - postgres
      - redis
      - llm
    ports:
      - 8003:8003
    volumes:
      - ./youtube:/usr/src/app:ro
    env_file:
      - ./youtube/.env
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8003
      "

  reddit:
    build: ./reddit
    depends_on:
      - postgres
      - redis
      - llm
    ports:
      - 8002:8002
    volumes:
      - ./reddit:/usr/src/app:ro
    env_file:
      - ./reddit/.env
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8002
      "

  llm:
    build: ./llm
    depends_on:
      - ollama
    ports:
      - 8004:8004
    volumes:
      - ./llm:/usr/src/app:ro
    env_file:
      - ./llm/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004

  postgres:
    image: postgres:15
    env_file:
      - ./youtube/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - LLM_MODEL=tinyllama
    command: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull tinyllama &&
      wait
      "

volumes:
  postgres-db:
  redis-data:
  ollama-data:
