"""add unique video ids

Revision ID: 0028a87bbf03
Revises: 84a9cf7786db
Create Date: 2026-03-10 22:54:44.214120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0028a87bbf03'
down_revision: Union[str, Sequence[str], None] = '84a9cf7786db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'videos', ['video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    # ### end Alembic commands ###
