"""video_db_id as foreign keys

Revision ID: 035c5e921f7f
Revises: d0fcf7ec10b5
Create Date: 2026-03-20 06:04:40.650294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035c5e921f7f'
down_revision: Union[str, Sequence[str], None] = 'd0fcf7ec10b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'videos', ['video_db_id'], ['id'], ondelete='CASCADE')
    op.alter_column('predicted_titles', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'predicted_titles', 'videos', ['video_db_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predicted_titles', type_='foreignkey')
    op.alter_column('predicted_titles', 'score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
