"""changing the type of channel id

Revision ID: 06c35223c7b7
Revises: 590886e3adf7
Create Date: 2026-02-28 22:46:30.129451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c35223c7b7'
down_revision: Union[str, Sequence[str], None] = '590886e3adf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('channels_channel_id_key'), 'channels', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('channels_channel_id_key'), 'channels', ['channel_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
