"""removing user_id from channel table

Revision ID: 3f9fba052403
Revises: 06c35223c7b7
Create Date: 2026-02-28 23:25:01.968030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9fba052403'
down_revision: Union[str, Sequence[str], None] = '06c35223c7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('channels_user_id_fkey'), 'channels', type_='foreignkey')
    op.drop_column('channels', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('channels_user_id_fkey'), 'channels', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
