"""add video table

Revision ID: 84a9cf7786db
Revises: 3f9fba052403
Create Date: 2026-03-10 22:45:07.239742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a9cf7786db'
down_revision: Union[str, Sequence[str], None] = '3f9fba052403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('video_title', sa.String(), nullable=False),
    sa.Column('video_description', sa.String(), nullable=True),
    sa.Column('published_at', sa.String(), nullable=False),
    sa.Column('channel_id_url', sa.String(), nullable=False),
    sa.Column('channel_db_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_db_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
