"""update channels table

Revision ID: 8d9869a4e289
Revises: 61b3dbb7a103
Create Date: 2026-02-27 15:06:39.231074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9869a4e289'
down_revision: Union[str, Sequence[str], None] = '61b3dbb7a103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('total_no_of_videos', sa.Integer(), nullable=True))
    op.alter_column('channels', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('channels', 'subscriber_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'subscriber_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('channels', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('channels', 'total_no_of_videos')
    # ### end Alembic commands ###
