"""fix_video_metrics_unique_constraint

Revision ID: a99f95b335ce
Revises: aedf15b9381b
Create Date: 2026-03-12 22:43:35.244650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99f95b335ce'
down_revision: Union[str, Sequence[str], None] = 'aedf15b9381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('video_metrics_video_db_id_key'), 'video_metrics', type_='unique')
    op.create_unique_constraint('uq_video_db_id_date', 'video_metrics', ['video_db_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_video_db_id_date', 'video_metrics', type_='unique')
    op.create_unique_constraint(op.f('video_metrics_video_db_id_key'), 'video_metrics', ['video_db_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
