"""adding channel handle in channels table

Revision ID: 9e5461a4bb91
Revises: be030eeebf1c
Create Date: 2026-02-27 23:12:03.108477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5461a4bb91'
down_revision: Union[str, Sequence[str], None] = 'be030eeebf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channel_handle', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'channel_handle')
    # ### end Alembic commands ###
