"""changing a column in channels table

Revision ID: be030eeebf1c
Revises: 8d9869a4e289
Create Date: 2026-02-27 22:24:10.539582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be030eeebf1c'
down_revision: Union[str, Sequence[str], None] = '8d9869a4e289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('upload_playlist', sa.String(), nullable=True))
    op.drop_column('channels', 'total_no_of_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('total_no_of_videos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('channels', 'upload_playlist')
    # ### end Alembic commands ###
